name: Fetch Events
on:
  schedule:
     - cron: "*/5 * * * *" 
  workflow_dispatch: # allow manual trigger

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Fetch API data
        run: |
          curl -s "${{ secrets.JIOHOTSTAR_API_URL }}" | jq '.' > jiohotstar.json
          curl -s "${{ secrets.WATCHO_API_URL }}" | jq '.' > watcho.json
          curl -s "${{ secrets.OTTPLAY_API_URL }}" | jq '.' > ottplay.json
          curl -s "${{ secrets.BINGE_API_URL }}" | jq '.' > binge.json
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
           if ! git diff --staged --quiet; then
            TZ=Asia/Kolkata
            export TZ
            git commit -m "Update events data - $(date +"%d/%m/%Y, %I:%M %p IST")"
            git push
          else
            echo "No changes to commit"
          fi
       
